-- Basic conf
require("core.plugins")
require("core.configs")
require("core.keymaps")

-- Plugins conf
require("plugins.mason")
require("plugins.lsp")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.kanagawa")
require("plugins.colorize")
require("plugins.null-ls")
require("plugins.outline")
require("plugins.toggleterm")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.autotag")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.dashboard")
